server:
  port: 6002

jwt:
  secret: Key#SuperSecret$PolyglotTest#JavaMicroservices#940527000

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
       routes:      
      - id: appventa
        uri: http://app-venta:91
        predicates:
          - Path=/MSventa/**
        filters:
          - StripPrefix=1
      - id: appusuario
        uri: http://app-usuario:84
        predicates:
          - Path=/appusuario/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appproducto
        uri: http://app-producto:90
        predicates:
          - Path=/MSproducto/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: apppersona
        uri: http://app-persona:95
        predicates:
          - Path=/MSpersona/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appgenEnumerador
        uri: http://app-genenumerador:105
        predicates:
          - Path=/MSgenEnumerador/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
           
  

  
